### PR TITLE
Remove the possibility to load jdbc drivers from modules

### PR DESCRIPTION
**Pull request by lgoltz**
This pull request fixes the failed ITs from PR #580 and extends the warnings of the ConnectionProviderManager to mention all the driver loaded before.

### CODE REVIEW

**Comment by tfr42** [comment]
@stephanr  please take a look on the provided PR

**Comment by tfr42** [comment]
Test scenario for this PR might be:
 - (re)load the workspace
 - request against WFS against a FeatureType against the database
 - request against WMS against a Layer against the database
 - check if there is a leak in the permgen space of the JVM with jvisualvm (Oracle JDK 7)

repeat this for at least n (>5) iterations with the following alternative setups:
- [ ] Testing Apache Tomcat 7 with postgres driver in WEB-INF-lib
- [ ] Testing Apache Tomcat 7 with postgres driver in shared location
- [ ] Testing Oracle WLS 12 with oracle driver in WEB-INF-lib
- [ ] Testing Oracle WLS 12 with oracle driver in shared location

**Comment by copierrj** [comment]
Mentioned tests are scheduled to be executed after the next release (containing this patch)

**Comment by tfr42** [comment]
Task to test this PR moved to issue #629

**Pull request merged**
