### PR TITLE
OGC GeoPackage implementation - 3.4

### PR DESCRIPTION
**Pull request by diegomigliavacca**
http://tracker.deegree.org/deegree-services/ticket/613

"The GeoPackage specification describes an open, standards-based, platform-independent, portable, self-describing, compact format for transferring geospatial information. It is a set of conventions for SQLite to store interoperable Features and/or Tiles on a common base" (opengis/geopackage GitHub repository).

For the feature part, the user needs to configure in Deegree:
an SQL feature store;
a WFS service;
a JDBC connection;
a Feature Layer.

For the tile part, the user needs to configure:
a WMTS service;
a Gpkg Tile Store;
a Tile Layer.

Configuration of a JDBC connection (example):

```
<JDBCConnection configVersion="3.0.0" xmlns="http://www.deegree.org/jdbc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.deegree.org/jdbc http://schemas.deegree.org/jdbc/3.0.0/jdbc.xsd">

 <Url>jdbc:sqlite:/home/user/World.gpkg</Url>
 <User>null</User>
 <Password>null</Password>

</JDBCConnection>
```

User and Password can just to be set to "null", given that GeoPackage is based on SQLite.

Configuration of a Gpkg Tile Store (example):

```
<GpkgTileStore xmlns="http://www.deegree.org/datasource/tile/gpkg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.deegree.org/datasource/tile/gpkg http://schemas.deegree.org/datasource/tile/gpkg/3.2.0/geopackage.xsd" configVersion="3.2.0">

  <TileDataSet>
    <Identifier>gpkg_tiledataset</Identifier>
    <File>home/user/World.gpkg</File>
    <TileMapping table="fromosm_tiles"/>
    <!-- [0..1]: the mime type of the desired image output format.   Default is image/png -->
    <ImageFormat>image/png</ImageFormat>
  </TileDataSet>

</GpkgTileStore>
```

### CODE REVIEW

**Comment by tfr42** [comment]
Thank you for your contribution. Your pull request has been discussed by the TMC today. Please see the following remarks from the TMC members:
 * We need at least some documentation for the deegree webservices handbook
 * And since it affects the deegree console we are in favor in move to a later stable release version of 3.4

However, we found that it is not ready yet for inclusion:
The TMC would be happy if can find the time to address these shortcomings and participate.

**Comment by diegomigliavacca** [comment]
I think it's a really good idea to move it to a later stable release version of 3.4.
I will test this implementation again in a later stable release and I will improve it.
I will contact you about documentation for the webservices handbook.

**Comment by tfr42** [comment]
Dear deegree users! If someone of you would like this PR merged and want this as an official part of deegree, then please act now. Either rebase and fix the build or post a comment. Otherwise we will close this PR soon.

**Comment by tfr42** [comment]
TMC consider this PR as very interesting and would like to continue. Volunteers are very welcome! Please get in contact with the TMC.

**Comment by tfr42** [comment]
Based on @diegomigliavacca work a new PR #1437 has been created to support target version 3.5

**Comment by stephanr** [comment]
The TMC decided to close this PR in favor of #1437 

* #1437

**Pull request closed without merging**
