### PR TITLE
Added support of GeoJSON

### PR DESCRIPTION
**Pull request by dstenger**
This PR adds GeoJSON as supported output format to WFS.

The implementation also enhances GeoJSON as other CRS than WGS84 can be returned if configured.

### CODE REVIEW

**Comment by tfr42** [comment]
Fixes #849

**Comment by tfr42** [comment]
This PR is included in PR #1164

**Comment by copierrj** [comment]
PR #1164 is merged. Please check manually if there are any more remaining changes in this PR that still needs merging.

**Comment by lgoltz** [comment]
No more changes left. PR can be closed.

**Comment by tfr42** [comment]
PR #1164 includes all changes of this PR. PR #1164 was merged. This PR can be closed.

**Pull request closed without merging**
