### PR TITLE
[GML_322_support] add GML 3.2.2 support

### PR DESCRIPTION
**Pull request by kad-switzc**
* Renamed existing version GML_32 to GML_321
* Added new verison GML_322
* Added a few tests to make sure the right version is picked.
* Modified a few methods to check for GML_321 and GML_322 instead of only to check for GML_321 (old GML_32)
* Left gml:id check intact for GML_321. In GML_322 gml:id is not required.

### CODE REVIEW

**Comment by tfr42** [comment]
@kad-switzc Thanks for contributing to the OSGeo project deegree. Since this is your first code contribution we kindly ask you to read the [deegree contribution guidelines](https://github.com/deegree/deegree3/blob/master/CONTRIB.md#legal) and confirm to by sending an email to the [deegree users mailing list](https://www.deegree.org/community/). Thanks!
And you can also prepare a PR to update the [list of contributors](https://github.com/deegree/deegree3/blob/master/CONTRIBUTORS.md) with your full name.

**Comment by tfr42** [comment]
@kad-switzc The TMC members like the PR a lot. Unfortunately the [integration tests](http://buildserver.deegree.org/view/Failing%20Jobs/job/deegree-3.4/job/pull-request/job/PR-1104/1/console) fail at a point where we expect that they should pass. The TMC members like the support of GML 3.2.2 in deegree. We are little bit hesitant to merge it because the PR changes the enumeration of GML versions. We are in favor to keep the existing one for GML 3.2.1 and add a new value for GML 3.2.2 only. 

And please check the information available in the wiki https://github.com/deegree/deegree3/wiki/Test-Practices and https://github.com/deegree/deegree3/wiki/Building-deegree3#running-integration-tests.

**Comment by tfr42** [comment]
@kad-switzc Thanks for confirming to the deegree contribution guidelines.

**Comment by copierrj** [comment]
After a lengthy discussion the TMC decided to make gml ids always optional. Although providing a gml id was mandatory in earlier versions of GML the OGC apparently decided to change the GML standard retroactively.

Therefore we decided to merge PR #1092 instead of yours. This change completely removes the gml id check. Some changes you proposed in this PR are however lifted out into PR #1108 in order to add support for 3.2.2.

**Pull request closed without merging**
