### PR TITLE
Fix for #531-3.3: CSW error when creating database tables

### PR DESCRIPTION
**Pull request by diegomigliavacca**
This pull request fixes the issue #531 in Deegree 3.3.

### CODE REVIEW

**Comment by tfr42** [comment]
A hint to the handbook should be added.

**Comment by copierrj** [comment]
Alternative solution: change the sql to use a conditional expression to differentiate the srs (0 for PostGIS 2 and -1 for PostGIS 1.5)

**Comment by tfr42** [comment]
The best approach is to use a conditional expression to differenciate between postgis 1.4, 1.5 and 2.0
in the Postgres dialect.

**Comment by tfr42** [comment]
Replaced by #658

**Pull request closed without merging**
