### PR TITLE
Find correct featureStore when inserting - 3.3

### PR DESCRIPTION
**Pull request by jarped**

### CODE REVIEW

**Comment by jarped** [comment]
I see some problems regarding featureCollections.

**Comment by tfr42** [comment]
#815 is PR for 3.4

**Comment by tfr42** [comment]
- [ ] The PR #815 needs rebase and hence we merge 3.3 and 3.4 in a row this PR is put on hold
- [ ] Our concern about this PR is that it handles not all cases when dealing with multiple FeatureStores. We would like to better understand what is the problem which is should be solved by this PR?

**Comment by copierrj** [comment]
This pull request seems stuck for quite a long time. Therefore the TMC decided to close this pull request.

Also note: the 3.3 branch is no longer supported and no subsequent releases are to be expected.

**Pull request closed without merging**
