### PR TITLE
PNG 8bit support

### PR DESCRIPTION
**Pull request by hwbllmnn**
Adds support for png 8bit indexed color model output images.

### CODE REVIEW

**Comment by copierrj** [comment]
Conflicts with #469

**Comment by tfr42** [comment]
Thank you for your contribution. Your pull request has been discussed by the TMC. Please see the following remarks from the TMC members:
 * copierrj stated that this PR conflicts with #469 and he is willing to rebase this PR later after #469 has been merged.

The TMC would be happy if can find the time to discuss this with copierrj.

**Comment by hwbllmnn** [comment]
Sure, if you/he have/has questions, just let me know.

**Comment by copierrj** [comment]
Thank you for your contribution. Your pull requests has been accepted by the TMC.
This pull request will be part of the 3.4-pre17 release.

**Pull request merged**
