### PR TITLE
SQLFeatureStore: Fix filtering on gml:identifier in BLOB mode

### PR DESCRIPTION
**Pull request by MrSnyder**
Before this patch, queries that filter based on the gml:identifier property would not match any features. The patches fixes that so the expected feature is returned. Test case included.

Depends on #665.

### CODE REVIEW

**Comment by copierrj** [comment]
The TMC reviewed this PR and decided that in order to consider it for merging it should be rebased first. Although not technically required by git, we would like to this PR to be rebuild / retested by travis using the pom.xml and travis configuration currently in master.

**Comment by copierrj** [comment]
Reminder to TMC: infrastructure changes as outlined in #851 should be finalized before merging this issue. Otherwise we might not be able to do release builds anymore!

**Comment by vog** [comment]
This pull request depends on #665, so it makes no sense to rebase it before #665 is resolved.

**Comment by tfr42** [comment]
Thank you for your contribution. Unfortunately, the TMC members came to the conclusion not to merge it into the deegree code base since the PR get stuck (see [PR marked for deletion](https://github.com/deegree/deegree3/wiki/Working-with-pull-requests#pull-requests-marked-for-deletion)). Of course this is not the final word. If you think, that we did wrong then please re-initiate the Decision Making Process by making a opening an updated pull request and taking the feedback from the TMC into consideration. Perhaps we can then merge that new pull request. Anyhow, we do appreciate your commitment to open source and to deegree in special.

**Pull request closed without merging**
