### PR TITLE
Altered epsg:3857 to use a spherical formula

### PR DESCRIPTION
**Pull request by jarped**
#663 backported to 3.3

### CODE REVIEW

**Comment by jarped** [comment]
Can't understand why Travis was unable to build. I see the problem was building with openjdk, whereas oraclejdk worked fine. Also, I've looked at the logfiles:

> [10:07:30]  WARN: [GmlDocumentIdContext] Unable to resolve external object reference: ***urn:cgi:classifier:CGI:GeologicUnitType:200811:lithodemic_unit***. Resolving of urn references is not implemented yet.

> [10:07:30]  WARN: [GmlDocumentIdContext] Unable to resolve external object reference: ***urn:cgi:classifier:CGI:GeologicUnitType:200811:geologic_unit***. Resolving of urn references is not implemented yet.

I have not put in anything like this. Color me confused.

**Comment by jarped** [comment]
Shouldn't the milestone be 3.3.19 btw?

**Comment by jarped** [comment]
Looking at Travis logs it seems oraclejdk never even started. Maybe try a restart?

**Comment by copierrj** [comment]
I've restarted the build. The openjdk build succeeded, so I don't think there is anything wrong with the pull request itself.

**Pull request merged**
