### PR TITLE
Fix Oracle 11g.R2 compability, upgrade Oracle Driver to 19.3.0.0 and remove use of profile for public available Oracle database drivers

### PR DESCRIPTION
**Pull request by dstenger**
Fix Oracle 11g.R2 compability, upgrade Oracle Driver to 19.3.0.0 and remove use of profile for public available Oracle database drivers.

Currently, the branch does not compile because dependency `com.oracle:xmlparserv2_sans_jaxp_services:jar:19.3.0.0` is not available.

### CODE REVIEW

**Comment by lgoltz** [comment]
This pull request based on one other pull request which should be merged first:
- https://github.com/deegree/deegree3/pull/1128

**Comment by dstenger** [comment]
Branch is compiling again and thus the pull request is ready to be merged.

**Comment by tfr42** [comment]
relates to #1128

**Comment by tfr42** [comment]
This PR fixes issue #1122

**Pull request merged**
