### PR TITLE
Tile store implementation for creating overlays of tile stores

### PR DESCRIPTION
**Pull request by MrSnyder**
Fixes pull request #250.
#250 pulled an obsolete branch, this is the up-to-date version which has a better name for the new module and handbook additions.

New deegree module:

deegree-tilestore-overlay: Allows to create overlays from tile stores on-the-fly

### CODE REVIEW

**Comment by tfr42** [comment]
Is this PR still valid? And shall this feature be part of the 3.4 release?

**Comment by MrSnyder** [comment]
I don't require it anymore, so please close it if nobody else has a strong opinion here.

**Comment by tfr42** [comment]
Dear all, if someone is using this PR already and want this as an official part of deegree, then please act now. Either rebase and fix the build or post a comment. Otherwise we will close this PR soon.

**Comment by tfr42** [comment]
Thank you for your contribution. Unfortunately, the TMC members came to the conclusion not to merge it into the deegree code base since the PR get stuck (see [PR marked for deletion](https://github.com/deegree/deegree3/wiki/Working-with-pull-requests#pull-requests-marked-for-deletion)). Of course this is not the final word. If you think, that we did wrong then please re-initiate the Decision Making Process by making a opening an updated pull request and taking the feedback from the TMC into consideration. Perhaps we can then merge that new pull request. Anyhow, we do appreciate your commitment to open source and to deegree in special.

**Pull request closed without merging**
