### PR TITLE
Fix missing JobBuilderFactory bean in GmlLoaderConfiguration

### LINKED ISSUE #1760: IllegalArgumentException while using the GmlLoader
After successfully testing the PR #1759, the following exception is thrown (stack trace):

```
2024-11-06 16:01:46 [main] INFO o.d.t.f.loader.GmlReader - Finished file SEISMIKLINIEN_INSPIRE_GE_angepasst_kurz.gml
2024-11-06 16:01:46 [main] ERROR o.s.batch.core.job.AbstractJob - Exception encountered in afterJob callback
java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.base/java.text.DateFormat.format(DateFormat.java:342)
	at java.base/java.text.Format.format(Format.java:159)
	at org.deegree.tools.featurestoresql.loader.ReportWriter.getStartTime(ReportWriter.java:137)
	at org.deegree.tools.featurestoresql.loader.ReportWriter.afterJob(ReportWriter.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.deegree.tools.featurestoresql.loader.ReportWriter$$SpringCGLIB$$0.afterJob(<generated>)
	at org.springframework.batch.core.listener.CompositeJobExecutionListener.afterJob(CompositeJobExecutionListener.java:60)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:370)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:157)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:148)
	at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:59)
	at org.deegree.tools.featurestoresql.SubcommandApp.runJob(SubcommandApp.java:46)
	at org.deegree.tools.featurestoresql.loader.GmlLoaderApp.run(GmlLoaderApp.java:48)
	at org.deegree.tools.featurestoresql.GmlToolsApp.main(GmlToolsApp.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
2024-11-06 16:01:46 [main] ERROR o.s.batch.core.job.AbstractJob - Exception encountered in afterJob callback
java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.base/java.text.DateFormat.format(DateFormat.java:342)
	at java.base/java.text.Format.format(Format.java:159)
	at org.deegree.tools.featurestoresql.loader.ReportWriter.getStartTime(ReportWriter.java:137)
	at org.deegree.tools.featurestoresql.loader.ReportWriter.afterJob(ReportWriter.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.deegree.tools.featurestoresql.loader.ReportWriter$$SpringCGLIB$$0.afterJob(<generated>)
	at org.springframework.batch.core.listener.CompositeJobExecutionListener.afterJob(CompositeJobExecutionListener.java:60)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:370)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:157)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:148)
	at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:59)
	at org.deegree.tools.featurestoresql.SubcommandApp.runJob(SubcommandApp.java:46)
	at org.deegree.tools.featurestoresql.loader.GmlLoaderApp.run(GmlLoaderApp.java:48)
	at org.deegree.tools.featurestoresql.GmlToolsApp.main(GmlToolsApp.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
2024-11-06 16:01:46 [main] ERROR o.s.batch.core.job.AbstractJob - Exception encountered in afterJob callback
java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.base/java.text.DateFormat.format(DateFormat.java:342)
	at java.base/java.text.Format.format(Format.java:159)
	at org.deegree.tools.featurestoresql.loader.ReportWriter.getStartTime(ReportWriter.java:137)
	at org.deegree.tools.featurestoresql.loader.ReportWriter.afterJob(ReportWriter.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at org.deegree.tools.featurestoresql.loader.ReportWriter$$SpringCGLIB$$0.afterJob(<generated>)
	at org.springframework.batch.core.listener.CompositeJobExecutionListener.afterJob(CompositeJobExecutionListener.java:60)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:370)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:157)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:148)
	at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:59)
	at org.deegree.tools.featurestoresql.SubcommandApp.runJob(SubcommandApp.java:46)
	at org.deegree.tools.featurestoresql.loader.GmlLoaderApp.run(GmlLoaderApp.java:48)
	at org.deegree.tools.featurestoresql.GmlToolsApp.main(GmlToolsApp.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
2024-11-06 16:01:46 [main] INFO o.s.b.c.l.support.SimpleJobLauncher - Job: [SimpleJob: [name=gmlLoaderJob]] completed with the following parameters: [{'pathToFile':'{value=/root/.deegree/geophysics/data/SEISMIKLINIEN_INSPIRE_GE_angepasst_kurz.gml, type=class java.lang.String, identifying=true}','workspaceName':'{value=geophysics, type=class java.lang.String, identifying=true}','disabledResources':'{value=https://inspire.ec.europa.eu/codelist/, type=class java.lang.String, identifying=true}','sqlFeatureStoreId':'{value=GeophysicsCore, type=class java.lang.String, identifying=true}'}] and the following status: [COMPLETED] in 6s411ms
2024-11-06 16:01:46 [main] INFO o.s.b.c.l.support.SimpleJobLauncher - Job: [SimpleJob: [name=gmlLoaderJob]] completed with the following parameters: [{'pathToFile':'{value=/root/.deegree/geophysics/data/SEISMIKLINIEN_INSPIRE_GE_angepasst_kurz.gml, type=class java.lang.String, identifying=true}','workspaceName':'{value=geophysics, type=class java.lang.String, identifying=true}','disabledResources':'{value=https://inspire.ec.europa.eu/codelist/, type=class java.lang.String, identifying=true}','sqlFeatureStoreId':'{value=GeophysicsCore, type=class java.lang.String, identifying=true}'}] and the following status: [COMPLETED] in 6s411ms
2024-11-06 16:01:46 [main] INFO o.s.b.c.l.support.SimpleJobLauncher - Job: [SimpleJob: [name=gmlLoaderJob]] completed with the following parameters: [{'pathToFile':'{value=/root/.deegree/geophysics/data/SEISMIKLINIEN_INSPIRE_GE_angepasst_kurz.gml, type=class java.lang.String, identifying=true}','workspaceName':'{value=geophysics, type=class java.lang.String, identifying=true}','disabledResources':'{value=https://inspire.ec.europa.eu/codelist/, type=class java.lang.String, identifying=true}','sqlFeatureStoreId':'{value=GeophysicsCore, type=class java.lang.String, identifying=true}'}] and the following status: [COMPLETED] in 6s411ms
```

### PR DESCRIPTION
**Pull request by julianzz98**
This PR fixes an exception caused by a missing JobBuilderFactory bean in the GmlLoaderConfiguration class.

The initial stack trace of the exception that was thrown when using the GmlLoader:
```
024-11-06 13:08:24 [main] WARN o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gmlLoaderConfiguration': Unsatisfied dependency expressed through field 'jobBuilderFactory': No qualifying bean of type 'org.springframework.batch.core.configuration.annotation.JobBuilderFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2024-11-06 13:08:24 [main] WARN o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gmlLoaderConfiguration': Unsatisfied dependency expressed through field 'jobBuilderFactory': No qualifying bean of type 'org.springframework.batch.core.configuration.annotation.JobBuilderFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gmlLoaderConfiguration': Unsatisfied dependency expressed through field 'jobBuilderFactory': No qualifying bean of type 'org.springframework.batch.core.configuration.annotation.JobBuilderFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:787)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1421)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:93)
	at org.deegree.tools.featurestoresql.loader.GmlLoaderApp.run(GmlLoaderApp.java:46)
	at org.deegree.tools.featurestoresql.GmlToolsApp.main(GmlToolsApp.java:23)
	... 7 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.batch.core.configuration.annotation.JobBuilderFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1880)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784)
	... 23 more
```

Closes #1760

### CODE REVIEW

**Comment by julianzz98** [comment]
The PR was successfully tested on a local environment using the main branch. Nevertheless, the bug documented in #1760 still persists.

**Comment by lgoltz** [comment]
> The PR was successfully tested on a local environment using the main branch. Nevertheless, the bug documented in https://github.com/deegree/deegree3/issues/1760 still persists.

Fixed with commit https://github.com/deegree/deegree3/pull/1759/commits/5c32ee48127178714702179591b6196b929047f5

**Comment by stephanr** [comment]
In the TMC meeting on 2024-11-20 the additional information was given, that having a database is now required dependency since we moved to the latest spring boot/batch.

**Review by stephanr — APPROVED** [review]

**Comment by tfr42** [comment]
The Database is required with Spring Boot 3.x and Spring Batch 5.x: https://docs.spring.io/spring-boot/how-to/batch.html

**Pull request merged**
