### PR TITLE
Fix #848 [SQLFeatureStore] Deleting features fails for certain feature type prefix configurations (3.3-backport)

### LINKED ISSUE #848: [SQLFeatureStore] Deleting features fails for certain feature type prefix configurations
We observed that a delete by feature id against an SQLFeatureStore fails in some cases. This issue seems to be related to certain feature prefix configuration and differs between Java versions, e.g. we have two feature types with the following feature id prefices:

* APP_FEATURE_
* APP_FEATURE_X

We found that deleting the feature with id "APP_FEATURE_X_1" works in a Java 7 setup (tested with OpenJDK 7, 1.7.0_151 on Ubuntu 14.04 AMD64), while it fails with an exception on Java 8 (same machine, Oracle JDK 8, 1.8.0_144).

A first analysis points to method analyze(String) in class org.deegree.feature.persistence.sql.id.IdAnalyzer:

<pre>
...
        // TODO implement this more efficiently
        for ( String prefix : prefixToFt.keySet() ) {
            if ( featureOrGeomId.startsWith( prefix ) ) {
                ft = prefixToFt.get( prefix );
                break;
            }
        }
...
</pre>

We believe this is caused by the different key order in the respective HashMap implementations:

https://stackoverflow.com/questions/38587711/hashmap-keyset-returns-keys-in-different-order-in-java-7-java-8

### PR DESCRIPTION
**Pull request by MrSnyder**
Same as PR #867, backported to deegree 3.3.

### CODE REVIEW

**Comment by copierrj** [comment]
Thank you for your contribution. The TMC meeting noticed that your PR contains a change to the .travis.yml file. It was therefore decided that we would to ask you if you can remove this change.

**Comment by stephanr** [comment]
While talking in the TMC meeting we noticed that the code formating changed on an existing File.
This is not a problem by itself but raises the chance that merge conflict can arise. 
So may it be possible that you are not using the eclipse based formatting file described in the wiki [1] ?

[1] https://github.com/deegree/deegree3/wiki/Setting-up-deegree3-in-your-IDE#use-the-deegree3-formatter

**Comment by MrSnyder** [comment]
Hi Reijer,

without the change to .travis.yml, the CI build fails (due to Oracle 7 JDK not being available on Travis anymore). I just removed it, but now the CI issue is back. How shall we go about that?

Best regards,
Markus

**Comment by copierrj** [comment]
@MrSnyder This travis issue was already fixed for master and I overlooked that your PR is for 3.3-master. 

The TMC likes to separate infrastructure related stuff (e.g. travis config) from actual changes to the codebase by creating separate issues and pull request for those. 

We'll fix the travis issue asap (which should result in the travis check no longer failing) and come back to your pull request.

Related intrastructure PR: #869

**Comment by MrSnyder** [comment]
Ok, I hope that does it:

- Rebased on #869 (thx, Reijer)
- Fixed code formatting issue

**Pull request merged**
