### PR TITLE
Remove the possibility to load jdbc drivers from modules 

### PR DESCRIPTION
**Pull request by stephanr**
This pull request is a possible soultion to prevent dangerous classloader usage and targetes as an alternative to pr #572.

The provided solution is to follow the commonly used method to only use jdbc drivers which are available either by the system (shared or server libraries) or by the application (WEB-INF/lib).

This pull would remove the code which would register jdbc drivers available in the modules folder.
So the need to deregister jdbc drivers (and to fix resulting classloader issues) is not needed any more.

After the talks about the problem with @tfr42 and @hwbllmnn at the FossGIS Hacking Event yesterday, i came to the conclusion that a testing of the most commonly use cases will be required.

So the test scenario may could look like N (20?) iterations of the following:
 - (re)load the workspace
 - request against WFS against a FeatureType against the database
 - request against WMS against a Layer against the database

To check if there is a leak the perm gen space has to be set to a small value and should be monitored by jvisualvm for example.

For the most commonly used database drivers i would like to suggest postgres and oracle drivers as they are relevant in this case.
- [ ] Testing tomcat with postgres driver in WEB-INF-lib
- [ ] Testing tomcat with postgres driver in shared location
- [ ] Testing tomcat with oracle driver in WEB-INF-lib
- [ ] Testing tomcat with oracle driver in shared location
- [ ] Maybe testing in an application server is also required

### CODE REVIEW

**Comment by copierrj** [comment]
Needs manual building and testing

**Comment by tfr42** [comment]
See comment in #572 for further information. This should be added to handbook IMO.

**Comment by copierrj** [comment]
Tried to build (mvn clean install) this PR locally:

Tests in error:
  

RemoteWMSTileStoreTest.testGetTileMatrixSetEPSG26912:109 NullPointer
  RemoteWMSTileStoreTest.testGetMetdataEPSG26912:97 NullPointer

Surefire reports:
[TEST-org.deegree.tile.persistence.remotewms.RemoteWMSTileStoreTest.xml](https://github.com/deegree/deegree3/files/10650/TEST-org.deegree.tile.persistence.remotewms.RemoteWMSTileStoreTest.xml.txt)
[org.deegree.tile.persistence.remotewms.RemoteWMSTileStoreTest.txt]
(https://github.com/deegree/deegree3/files/10647/org.deegree.tile.persistence.remotewms.RemoteWMSTileStoreTest.txt)

CC: @dstenger

**Comment by dstenger** [comment]
@copierrj, we could not reproduce your result.

When trying to build the branch (mvn clean install -Pintegration-tests,oracle,mssql,handbook), same tests as in travic-ci job fail:
```
Tests in error: 
  WMSCite111IntegrationTest.singleTest:103 Runtime Test 'wms:wms_main' failed.
  WMSCite111IntegrationTest.singleTest:103 Runtime Test 'wms:profiles-queryable-...
  WMSCite111IntegrationTest.singleTest:103 Runtime Test 'wms:profiles-queryable-...
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'main:main' failed.
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'main:options-require...
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'main:std-data-presen...
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'main:std-data-querya...
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'main:vector_elevatio...
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'main:time' failed.
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'dims:main' failed.
  WMSCite130NewIntegrationTest.singleTest:103 Runtime Test 'dims:terrain-and-oth...
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'main:main' failed.
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'main:queryable-profile'...
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'main:std-data-present' ...
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'main:std-data-queryable...
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'getmap:main' failed.
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'getmap:bbox-pixel-inter...
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'getmap:bgcolor' failed.
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'getmap:no-bgcolor' fail...
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'getmap:blue-bgcolor' fa...
  WMSCite130IntegrationTest.singleTest:103 Runtime Test 'getmap:transparent-true...
  WFSCite110IntegrationTest.singleTest:104 Runtime Test 'wfs:wfs-main' failed.
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:main' failed.
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
  WFSCite100IntegrationTest.singleTest:136 Runtime Test 'wfs:test1.0.0-basic-get...
```

**Comment by copierrj** [comment]
Still needs more testing. Proposed changes could result in workspace initialization issues causing the integration tests to fail.

**Pull request merged**
